### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by topolik** [holatuwol/liferay-intellij#2]
Hi Minhchau,

looks like `io.netty:netty-codec-http2:4.1.0.Final` has 151920 entries inside.

Calling `push.apply()` https://github.com/holatuwol/liferay-intellij/blob/6571ed002245f05763638627228608f0f93c6c24/streams0/streams9.js#L354 with 151920 arguments throws this:
```js
 ╭╴ 10:58:33 (7.0.x) /opt/liferay.git/portal-7.0.x
 ╰╴ ij /opt/liferay.git/portal-7.0.x-private/
Running npm/yarn to update script dependencies
npm WARN package.json liferay-intellij@1.0.0 No repository field.
Scanning /opt/liferay.git/portal-7.0.x-private/
Scanning /opt/liferay.git/portal-7.0.x
Processing dependency versions
Processing dependency artifacts
Generating IntelliJ workspace
events.js:141
      throw er; // Unhandled 'error' event
      ^

RangeError: Maximum call stack size exceeded
    at getLibraryTableXML (/opt/liferay-intellij.git/streams0/streams9.js:354:24)
    at getLibraryXML (/opt/liferay-intellij.git/streams0/streams9.js:384:12)
    at /opt/liferay-intellij.git/node_modules/highland/lib/index.js:1714:25
    at Stream.s._send (/opt/liferay-intellij.git/node_modules/highland/lib/index.js:1285:9)
    at Stream.write (/opt/liferay-intellij.git/node_modules/highland/lib/index.js:1375:18)
    at Stream._send (/opt/liferay-intellij.git/node_modules/highland/lib/index.js:761:26)
    at push (/opt/liferay-intellij.git/node_modules/highland/lib/index.js:1250:19)
    at /opt/liferay-intellij.git/node_modules/highland/lib/index.js:1719:13
    at Stream.s._send (/opt/liferay-intellij.git/node_modules/highland/lib/index.js:1285:9)
    at Stream.write (/opt/liferay-intellij.git/node_modules/highland/lib/index.js:1375:18)
```

I looked into what it contains and there are many duplicates inside `binaryPaths` variable.

**Comment by holatuwol** [comment]
Fixed by https://github.com/holatuwol/liferay-intellij/pull/3
